-- Challenge 1 - Steve's Car Showroom
/*1. What are the details of all cars purchased in the year 2022?
2. What is the total number of cars sold by each salesperson?
3. What is the total revenue generated by each salesperson?
4. What are the details of the cars sold by each salesperson?
5. What is the total revenue generated by each car type?
6. What are the details of the cars sold in the year 2021 by salesperson 'Emily Wong'?
7. What is the total revenue generated by the sales of hatchback cars?
8. What is the total revenue generated by the sales of SUV cars in the year 2022?
9. What is the name and city of the salesperson who sold the most number of cars in the year 2023?
10. What is the name and age of the salesperson who generated the highest revenue in the year 2022?*/

--1. What are the details of all cars purchased in the year 2022?

select distinct cars.* from cars inner join sales on cars.car_id=sales.car_id where YEAR(purchase_date)=2022 order by car_id;

--2. What is the total number of cars sold by each salesperson?

select count(car_id) as no._of_car_sold, name from sales inner join salespersons on sales.salesman_id=salespersons.salesman_id group by name;

--3. What is the total revenue generated by each salesperson?

select sum(cost_$) as total_revenue, name from sales inner join salespersons on sales.salesman_id=salespersons.salesman_id
inner join cars on cars.car_id=sales.car_id group by salespersons.name;

--4. What are the details of the cars sold by each salesperson?

select cars.*, name from cars inner join sales on sales.car_id= cars.car_id inner join salespersons on sales.salesman_id=salespersons.salesman_id order by car_id;

--5. What is the total revenue generated by each car type?

SELECT type,sum(cost_$) from cars group by type;

--6. What are the details of the cars sold in the year 2021 by salesperson 'Emily Wong'?

select cars.* from cars inner join sales on sales.car_id=cars.car_id inner join 
salespersons on sales.salesman_id=salespersons.salesman_id where salespersons.name='emily wong' and year(purchase_date) =2021;

--7. What is the total revenue generated by the sales of hatchback cars?

select sum(cost_$) from cars inner join sales on sales.car_id= cars.car_id where style='hatchback' group by cars.car_id;

--8. What is the total revenue generated by the sales of SUV cars in the year 2022?

select sum(cost_$) as total_revenue from cars inner join sales on cars.car_id=sales.car_id where style='suv' and year(purchase_date)=2022;

--9. What is the name and city of the salesperson who sold the most number of cars in the year 2023?

with cte as (select COUNT(sales.salesman_id) over(partition by sales.salesman_id,year(purchase_date)) as no_of_cars, name,city from sales 
inner join salespersons on sales.salesman_id=salespersons.salesman_id where year(purchase_date)=2023)
select top 1 name, city from cte order by no_of_cars desc;

--10. What is the name and age of the salesperson who generated the highest revenue in the year 2022?

select top 1 name,age,sum(cost_$) as revenue from salespersons inner join sales on sales.salesman_id=salespersons.salesman_id 
inner join cars on cars.car_id=sales.car_id where year(purchase_date)=2022 group by name,age order by sum(cost_$) desc;


